//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1_Serv_WEB_prog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.SageBooks = new HashSet<SageBook>();
        }
    
        public int IdBook { get; set; }
        public string name { get; set; }
        public Nullable<int> pages { get; set; }
        public byte[] photo { get; set; }
    
        public virtual ICollection<SageBook> SageBooks { get; set; }
    }
}
