//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1_Serv_WEB_prog
{
    using System;
    using System.Collections.Generic;
    
    public partial class SageBook
    {
        public int IdSageBook { get; set; }
        public int IdBook { get; set; }
        public int IdSage { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Sage Sage { get; set; }
    }
}
